import React from 'react';
import {
  LayoutDashboard,
  Users,
  Megaphone,
  Video,
  Lightbulb,
  Compass,
  Handshake,
  Bot,
  BarChart,
  Settings,
  FolderOpen,
  Layout,
  MessageSquare,
  Activity,
  FileSpreadsheet,
  BookOpen,
  DollarSign,
  FileText,
  Building2,
  UserCheck,
  Heart,
  Briefcase,
  Star,
  Flame,
  Globe,
  ClipboardList
} from 'lucide-react';
import type { IconKey } from '../../config/navigation';

export const IconRegistry: Record<IconKey, React.ComponentType<{ size?: number; className?: string }>> = {
  dashboard:     LayoutDashboard,
  business:      Building2,
  crm:           Handshake,
  content:       Layout,
  ai:            Bot,
  reports:       BarChart,
  reportsCenter: FileSpreadsheet,
  documentation: BookOpen,
  system:        Settings,
  settings:      Settings,
  media:         FolderOpen,
  support:       MessageSquare,
  marketing:     Megaphone,
  creator:       Video,
  innovation:    Lightbulb,
  futureVision:  Compass,
  partnerships:  Handshake,
  operations:    Activity,
  finance:       DollarSign,
  invoices:      FileText,
  quotes:        ClipboardList,
  contacts:      UserCheck,
  supporters:    Heart,
  collaborators: Star,
  leads:         Flame,
  projects:      Briefcase,
  portfolio:     Globe,
  services:      Layout,
  users:         Users,
};
