export enum Role {
  OWNER = "OWNER",
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  EDITOR = "EDITOR",
  MANAGER = "MANAGER",
  SUPPORT = "SUPPORT",
  FINANCE = "FINANCE",
  DEVELOPER = "DEVELOPER",
  CUSTOMER = "CUSTOMER"
}

